In [1]:
import numpy as np
import cv2
import os

ModuleNotFoundError: No module named 'cv2'

In [2]:
pip install opencv-python

Note: you may need to restart the kernel to use updated packages.Collecting opencv-python
  Using cached opencv_python-4.8.0.76-cp37-abi3-win_amd64.whl (38.1 MB)



'DOSKEY' is not recognized as an internal or external command,
operable program or batch file.

[notice] A new release of pip available: 22.2.2 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np
import cv2
import os

In [4]:
# Define a function to convert images to matrices
def images_to_matrix(image_folder):
    i = 0 
    image_matrix = []
    for filename in os.listdir(image_folder):
        img = cv2.imread(os.path.join(image_folder, filename))
        if img is not None:
            # Resize and normalize the image
            print(i)
            img = img.astype('float32') / 255.0  # Normalize to [0, 1]
            image_matrix.append(img)
            i = i + 1
    return np.array(image_matrix)

In [5]:
# Specify your image folder
image_folder = r'C:\Users\NISHANT\Downloads\GrapesNet\GrapesNet\Dataset 1\Dataset 1(a)'

# Convert images to matrices
data_matrix = images_to_matrix(image_folder)

1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1


In [9]:
print(data_matrix.shape)

(2842, 500, 500, 3)


In [11]:
print(data_matrix[0].shape)

(500, 500, 3)


In [12]:
print(data_matrix[0])

[[[0.08627451 0.5254902  0.40784314]
  [0.05490196 0.49803922 0.36862746]
  [0.03529412 0.47843137 0.34509805]
  ...
  [0.09019608 0.8745098  0.80784315]
  [0.09019608 0.8862745  0.827451  ]
  [0.07450981 0.8862745  0.827451  ]]

 [[0.04313726 0.4862745  0.3529412 ]
  [0.05490196 0.49803922 0.3647059 ]
  [0.03137255 0.47058824 0.3372549 ]
  ...
  [0.08235294 0.76862746 0.6901961 ]
  [0.11764706 0.8117647  0.73333335]
  [0.09019608 0.7882353  0.7137255 ]]

 [[0.02745098 0.47843137 0.32156864]
  [0.03921569 0.48235294 0.33333334]
  [0.         0.42745098 0.3019608 ]
  ...
  [0.         0.42745098 0.30588236]
  [0.         0.42352942 0.3137255 ]
  [0.         0.35686275 0.24705882]]

 ...

 [[0.12941177 0.14901961 0.16078432]
  [0.15294118 0.17254902 0.18431373]
  [0.13725491 0.16470589 0.1764706 ]
  ...
  [0.32941177 0.36078432 0.35686275]
  [0.3254902  0.35686275 0.3529412 ]
  [0.3254902  0.35686275 0.3529412 ]]

 [[0.10196079 0.12156863 0.13333334]
  [0.11764706 0.13725491 0.14901961]
